### ISSUE TITLE
Filtering of event types on client or server side?

### ISSUE THREAD

**Issue by Niklas-Peter** [AxonIQ/axon-server-se#87]
Setup: Applications A and B based on Axon Framework connected to Axon Server (used as event store and event bus).

If A publishes an event of type T, which B does _not_ have any event handlers for: Is this event still delivered by Axon Server to B, so that B must determine locally, that it has no handlers for this type and that it can just ignore this event?
In other words: Is the event stream filtered by the event type on client or on server side? 

I have already analyzed the source code of Axon Framework and Axon Server SE, but I could not find any clues for filtering on the server side. It seems, as if Axon Server transmits all the published events to each tracking event processor on the client, which then checks whether he has an appropriate event handler. However, I do not understand, why it should have been done this way, because it would unnecessarily cause communication costs between the clients and Axon Server.

Thanks in advance!

**Comment by abuijze** [comment]
Hi Nicklas,

event filtering does happen on the server side, but not proactively. Essentially, AxonServer will always transmit _all_ events to the client. As the client receives message types that it will c ertainly never process, it will blacklist them. This list is shared on the connection, across to AxonServer. As long as that connection is alive, then the message will not be transmitted again. If the connection is re-established, for some reason, the blacklist on the server side will need to be rebuilt (which will eventually happen).

Note that this feature was added in 4.2 (and require both Framework and Server at 4.2+).

PS. For questions, please use our mailinglist instead of the issue tracker (axonframework@googlegroups.com or https://groups.google.com/forum/#!forum/axonframework). Thanks.
